[build]
  # Publish directory containing only the static frontend assets
  publish = "public"

[[redirects]]
  # Redirect any backend API call to the hosted Flask server instance
  from = "/api/*"
  to = "https://medicalreport-summarizer.onrender.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
